% subject 1
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','000-AO-curated.set','filepath','C:\\Users\\anhtn\\OneDrive - PennO365\\Documents\\GitHub\\AO_human_v_robot_main\\prelim_EEG\\datasets\\');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
pop_eegplot( EEG, 1, 1, 1);
EEG = pop_epoch( EEG, {  '10'  '11'  '12'  '13'  '14'  '20'  '21'  '22'  '23'  '24'  '30'  '31'  '32'  '33'  '34'  '40'  '41'  '42'  '43'  '44'  '50'  '51'  '52'  }, [-3         4.5], 'newname', '000-AO-curated epochs', 'epochinfo', 'yes');
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'gui','off'); 
pop_eegplot( EEG, 1, 1, 1);
EEG = pop_runica(EEG, 'icatype', 'picard', 'maxiter',500,'mode','standard');
[ALLEEG, EEG, CURRENTSET] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = pop_iclabel(EEG, 'default');
[ALLEEG, EEG, CURRENTSET] = eeg_store(ALLEEG, EEG, CURRENTSET);
figure; pop_spectopo(EEG, 0, [-3000      4492.1875], 'EEG' , 'freq', [10], 'plotchan', 0, 'percent', 20, 'icacomps', [1:32], 'nicamaps', 5, 'freqrange',[2 25],'electrodes','off');
EEG = pop_icflag(EEG, [NaN NaN;0.7 1;0.7 1;0.7 1;NaN NaN;0.7 1;NaN NaN]);
[ALLEEG, EEG, CURRENTSET] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = pop_subcomp( EEG, [], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 2,'gui','off'); 
pop_eegplot( EEG, 0, 1, 1);
pop_eegplot( EEG, 1, 1, 1);
EEG = pop_select( EEG, 'rmchannel',{'FP1','FP2'});
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 3,'gui','off'); 
figure; pop_spectopo(EEG, 1, [-3000      4492.1875], 'EEG' , 'freq', [6 10 22], 'freqrange',[2 25],'electrodes','off');
pop_eegplot( EEG, 0, 1, 1);
pop_eegplot( EEG, 1, 1, 1);
EEG = pop_rejepoch( EEG, [7 31 86 102 109 122 124] ,0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 4,'setname','000-AO-reject bad epochs','gui','off'); 
EEG = pop_select( EEG, 'rmchannel',{'O2'});
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 5,'gui','off'); 
figure; pop_spectopo(EEG, 1, [-3000      4492.1875], 'EEG' , 'freq', [6 10 22], 'freqrange',[2 55],'electrodes','off');
EEG = pop_runica(EEG, 'icatype', 'picard', 'maxiter',500,'mode','standard');
[ALLEEG, EEG, CURRENTSET] = eeg_store(ALLEEG, EEG, CURRENTSET);
pop_eegplot( EEG, 0, 1, 1);
EEG = pop_iclabel(EEG, 'default');
[ALLEEG, EEG, CURRENTSET] = eeg_store(ALLEEG, EEG, CURRENTSET);
figure; pop_spectopo(EEG, 0, [-3000      4492.1875], 'EEG' , 'freq', [10], 'plotchan', 0, 'percent', 20, 'icacomps', [1:29], 'nicamaps', 5, 'freqrange',[2 55],'electrodes','off');
EEG = pop_reref( EEG, []);
EEG = pop_reref( EEG, [],'interpchan',[]);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 6,'setname','000-AO-reref','gui','off'); 
figure; pop_spectopo(EEG, 1, [-3000      4492.1875], 'EEG' , 'freq', [6 10 22], 'freqrange',[2 25],'electrodes','off');
figure; pop_erpimage(EEG,1, [1],[[]],'Cz',10,1,{},[],'' ,'yerplabel','\muV','erp','on','cbar','on','topo', { [1] EEG.chanlocs EEG.chaninfo } );
figure; pop_timtopo(EEG, [-3000      4492.1875], [NaN], 'ERP data and scalp maps of 000-AO-reref');
pop_eegplot( EEG, 1, 1, 1);

% attempt: 2
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','000-AO-curated.set','filepath','C:\\Users\\anhtn\\OneDrive - PennO365\\Documents\\GitHub\\AO_human_v_robot_main\\prelim_EEG\\datasets\\');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = pop_eegfiltnew(EEG, 'locutoff',3,'plotfreqz',1);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'setname','000-AO-filter highpass','gui','off'); 
figure; pop_spectopo(EEG, 1, [0      2042992.1875], 'EEG' , 'freq', [6 10 22], 'freqrange',[2 55],'electrodes','off');
EEG = pop_select( EEG, 'rmchannel',{'FP1','FP2'});
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 2,'setname','000-AO-remove bad channel','gui','off'); 
figure; pop_spectopo(EEG, 1, [0      2042992.1875], 'EEG' , 'freq', [6 10 22], 'freqrange',[2 25],'electrodes','off');
EEG = pop_reref( EEG, []);
EEG = pop_reref( EEG, [],'interpchan',[]);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 3,'setname','000-AO-reref','gui','off'); 
figure; pop_spectopo(EEG, 1, [0      2042992.1875], 'EEG' , 'freq', [6 10 22], 'freqrange',[2 25],'electrodes','off');
EEG = pop_clean_rawdata(EEG, 'FlatlineCriterion',5,'ChannelCriterion',0.8,'LineNoiseCriterion',4,'Highpass','off','BurstCriterion',100,'WindowCriterion',0.3,'BurstRejection','on','Distance','Euclidian','WindowCriterionTolerances',[-Inf 7] );
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 4,'setname','000-AO-clean','gui','off'); 
figure; pop_spectopo(EEG, 1, [0      1383697.8337], 'EEG' , 'freq', [6 10 22], 'freqrange',[2 25],'electrodes','off');
EEG = pop_reref( EEG, [],'interpchan',[]);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 5,'setname','000-AO-clean reref','gui','off'); 
figure; pop_spectopo(EEG, 1, [0      1383697.8337], 'EEG' , 'freq', [6 10 22], 'freqrange',[2 25],'electrodes','off');
figure; topoplot([],EEG.chanlocs, 'style', 'blank',  'electrodes', 'labelpoint', 'chaninfo', EEG.chaninfo);
EEG = pop_runica(EEG, 'icatype', 'picard', 'maxiter',500,'mode','standard');
[ALLEEG, EEG, CURRENTSET] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = pop_iclabel(EEG, 'default');
[ALLEEG, EEG, CURRENTSET] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = pop_iclabel(EEG, 'default');
[ALLEEG, EEG, CURRENTSET] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = pop_icflag(EEG, [NaN NaN;0.7 1;0.7 1;NaN NaN;NaN NaN;NaN NaN;NaN NaN]);
[ALLEEG, EEG, CURRENTSET] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = pop_icflag(EEG, [NaN NaN;0.7 1;0.7 1;NaN NaN;NaN NaN;NaN NaN;NaN NaN]);
[ALLEEG, EEG, CURRENTSET] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = pop_subcomp( EEG, [], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 6,'gui','off'); 
figure; pop_spectopo(EEG, 0, [0      1383697.8337], 'EEG' , 'freq', [10], 'plotchan', 0, 'percent', 20, 'icacomps', [1:12], 'nicamaps', 5, 'freqrange',[2 25],'electrodes','off');
figure; pop_spectopo(EEG, 1, [0      1383697.8337], 'EEG' , 'freq', [6 10 22], 'freqrange',[2 25],'electrodes','off');
pop_eegplot( EEG, 1, 1, 1);
figure; topoplot([],EEG.chanlocs, 'style', 'blank',  'electrodes', 'numpoint', 'chaninfo', EEG.chaninfo);
EEG = pop_epoch( EEG, {  '10'  '11'  '12'  '13'  '14'  '20'  '21'  '22'  '23'  '24'  '30'  '31'  '32'  '33'  '34'  '40'  '41'  '42'  '43'  '44'  '50'  '51'  '52'  }, [-3         4.5], 'newname', '000-AO-clean reref pruned with ICA epochs', 'epochinfo', 'yes');
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 7,'gui','off'); 
pop_eegplot( EEG, 1, 1, 1);
figure; topoplot([],EEG.chanlocs, 'style', 'blank',  'electrodes', 'labelpoint', 'chaninfo', EEG.chaninfo);
EEG = pop_rejepoch( EEG, [4 7 45 54] ,0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 8,'gui','off'); 
figure; pop_spectopo(EEG, 1, [-3000      4492.1875], 'EEG' , 'freq', [6 10 22], 'freqrange',[2 25],'electrodes','off');
figure; pop_plottopo(EEG, [1:14] , '000-AO-clean reref pruned with ICA epochs', 0, 'ydir',1);
figure; pop_timtopo(EEG, [-3000      4492.1875], [NaN], 'ERP data and scalp maps of 000-AO-clean reref pruned with ICA epochs');
figure; pop_spectopo(EEG, 1, [-3000      4492.1875], 'EEG' , 'freq', [6 10 22], 'freqrange',[2 55],'electrodes','off');
